HPPFILE = obj.hpp he_mesh.hpp timer.hpp kdtree.hpp objProcessor.hpp linear.hpp utils.hpp pairHeap.hpp
CPP = main.cpp
FLAG = -std=c++11 -O3

main: $(CPP) $(HPPFILE)
	g++ $^ $(FLAG) -o $@


clear:
	rm main
